GET http://localhost:3000/tasks HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7ImlkIjo1MiwiZW1haWwiOiJ0ZXN0QGV4YW1wbGUuY29tIiwidXNlcm5hbWUiOiJ0ZXN0Iiwicm9vdCI6ZmFsc2UsImZpcnN0TmFtZSI6bnVsbCwibGFzdE5hbWUiOm51bGwsInBhc3N3b3JkIjoiJDJiJDEwJGpWNzM0WUZsSFNxWHZPSktGNW1PTmVCdXVhRW43akI3Si8zRFZEcWNUanoybkM1RTVmdFhDIiwiY3JlYXRlZEF0IjoiMjAyNC0wMy0zMFQxMTo0NTo1OC4yOTNaIiwidXBkYXRlZEF0IjoiMjAyNC0wMy0zMFQxMTo0NTo1OC4yOTNaIn0sImlhdCI6MTcxMTc5OTQyOSwiZXhwIjoxNzExODAzMDI5fQ.AzOWSnotVEcfhfPoPcWov27YEqlPxGWIAT5pEPlsfyw


###

#Criando usuario
POST http://localhost:3000/tasks HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7ImlkIjo1MiwiZW1haWwiOiJ0ZXN0QGV4YW1wbGUuY29tIiwidXNlcm5hbWUiOiJ0ZXN0Iiwicm9vdCI6ZmFsc2UsImZpcnN0TmFtZSI6bnVsbCwibGFzdE5hbWUiOm51bGwsInBhc3N3b3JkIjoiJDJiJDEwJGpWNzM0WUZsSFNxWHZPSktGNW1PTmVCdXVhRW43akI3Si8zRFZEcWNUanoybkM1RTVmdFhDIiwiY3JlYXRlZEF0IjoiMjAyNC0wMy0zMFQxMTo0NTo1OC4yOTNaIiwidXBkYXRlZEF0IjoiMjAyNC0wMy0zMFQxMTo0NTo1OC4yOTNaIn0sImlhdCI6MTcxMTc5OTQyOSwiZXhwIjoxNzExODAzMDI5fQ.AzOWSnotVEcfhfPoPcWov27YEqlPxGWIAT5pEPlsfyw

{
    "title": "Test"
}

###

#Atualizando usuario

PUT http:localhost:3000/tasks/1 HTTP/1.1

{
    
}

###

#Deletando usuario

DELETE http://localhost:3000/tasks/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7ImlkIjo1MiwiZW1haWwiOiJ0ZXN0QGV4YW1wbGUuY29tIiwidXNlcm5hbWUiOiJ0ZXN0Iiwicm9vdCI6ZmFsc2UsImZpcnN0TmFtZSI6bnVsbCwibGFzdE5hbWUiOm51bGwsInBhc3N3b3JkIjoiJDJiJDEwJGpWNzM0WUZsSFNxWHZPSktGNW1PTmVCdXVhRW43akI3Si8zRFZEcWNUanoybkM1RTVmdFhDIiwiY3JlYXRlZEF0IjoiMjAyNC0wMy0zMFQxMTo0NTo1OC4yOTNaIiwidXBkYXRlZEF0IjoiMjAyNC0wMy0zMFQxMTo0NTo1OC4yOTNaIn0sImlhdCI6MTcxMTc5OTQyOSwiZXhwIjoxNzExODAzMDI5fQ.AzOWSnotVEcfhfPoPcWov27YEqlPxGWIAT5pEPlsfyw

###
